# Generated by Django 4.1.7 on 2023-04-10 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('usrname', models.CharField(max_length=150, null=True, unique=True)),
                ('isActive', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_flavour', models.CharField(max_length=100, null=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('flavour', models.CharField(max_length=100, null=True)),
                ('kilojoules', models.IntegerField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('saturated_fat', models.FloatField(null=True)),
                ('carbohydrates', models.FloatField(null=True)),
                ('sugar', models.FloatField(null=True)),
                ('sodium', models.FloatField(null=True)),
                ('dietary_fiber', models.FloatField(null=True)),
                ('affiliate_link', models.CharField(max_length=200, null=True)),
                ('brand_affiliate', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('on_amazon', models.CharField(max_length=100, null=True)),
                ('amz_link', models.TextField(null=True)),
                ('asin', models.CharField(max_length=100, null=True)),
                ('protein', models.FloatField(null=True)),
                ('energy', models.CharField(max_length=100, null=True)),
                ('titel', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=300, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand')),
            ],
        ),
    ]
