# Generated by Django 4.1.7 on 2023-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_url_product_imag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imag_url2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
